export const UNIT_TYPES: { name: string; value: string }[] = [
  { name: "box", value: "box" },
  { name: "btl", value: "btl" },
  { name: "sqm", value: "sqm" },
  { name: "units", value: "units" },
  { name: "lots", value: "lots" },
  { name: "ctn", value: "ctn" },
  { name: "LT", value: "LT" },
  { name: "cm", value: "cm" },
  { name: "dz", value: "dz" },
  { name: "ft", value: "ft" },
  { name: "g", value: "g" },
  { name: "in", value: "in" },
  { name: "kg", value: "kg" },
  { name: "km", value: "km" },
  { name: "lg", value: "lg" },
  { name: "mg", value: "mg" },
  { name: "ml", value: "ml" },
  { name: "lb", value: "lb" },
  { name: "m", value: "m" },
  { name: "pcs", value: "pcs" },
];
